### PR TITLE
Re-render

### PR DESCRIPTION
**Pull request by ocefpaf**
@bekozi I should have done this a long time ago. Sorry for dropping the ball here.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Failing with:

```shell
======================================================================
ERROR: test_calc (ocgis.test.test_simple.test_simple.TestSimple)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/feedstock_root/build_artefacts/recipe_root_1486655374736/_t_env/lib/python2.7/site-packages/ocgis/test/test_simple/test_simple.py", line 590, in test_calc
    ret = self.get_ret(kwds={'calc': calc, 'calc_grouping': group, 'aggregate': True, 'calc_raw': calc_raw})
  File "/feedstock_root/build_artefacts/recipe_root_1486655374736/_t_env/lib/python2.7/site-packages/ocgis/test/test_simple/test_simple.py", line 91, in get_ret
    ret = OcgInterpreter(ops).execute()
  File "/feedstock_root/build_artefacts/recipe_root_1486655374736/_t_env/lib/python2.7/site-packages/ocgis/api/interpreter.py", line 125, in execute
    ret = conv.write()
  File "/feedstock_root/build_artefacts/recipe_root_1486655374736/_t_env/lib/python2.7/site-packages/ocgis/conv/numpy_.py", line 14, in write
    for coll in self:
  File "/feedstock_root/build_artefacts/recipe_root_1486655374736/_t_env/lib/python2.7/site-packages/ocgis/conv/numpy_.py", line 9, in __iter__
    for coll in self.colls:
  File "/feedstock_root/build_artefacts/recipe_root_1486655374736/_t_env/lib/python2.7/site-packages/ocgis/api/subset.py", line 75, in __iter__
    for coll in self._iter_collections_():
  File "/feedstock_root/build_artefacts/recipe_root_1486655374736/_t_env/lib/python2.7/site-packages/ocgis/api/subset.py", line 139, in _iter_collections_
    coll = self.cengine.execute(coll, file_only=self.ops.file_only, tgds=tgds)
  File "/feedstock_root/build_artefacts/recipe_root_1486655374736/_t_env/lib/python2.7/site-packages/ocgis/calc/engine.py", line 138, in execute
    out_vc = function.execute()
  File "/feedstock_root/build_artefacts/recipe_root_1486655374736/_t_env/lib/python2.7/site-packages/ocgis/calc/base.py", line 154, in execute
    self._execute_()
  File "/feedstock_root/build_artefacts/recipe_root_1486655374736/_t_env/lib/python2.7/site-packages/ocgis/calc/base.py", line 627, in _execute_
    fill = self._get_temporal_agg_fill_(value, shp_fill=shp_fill)
  File "/feedstock_root/build_artefacts/recipe_root_1486655374736/_t_env/lib/python2.7/site-packages/ocgis/calc/base.py", line 433, in _get_temporal_agg_fill_
    fill[ir, it, il, :, :] = self.aggregate_spatial(cc, weights)
  File "/feedstock_root/build_artefacts/recipe_root_1486655374736/_t_env/lib/python2.7/site-packages/ocgis/calc/base.py", line 119, in aggregate_spatial
    ret = np.ma.average(values, weights=weights)
  File "/feedstock_root/build_artefacts/recipe_root_1486655374736/_t_env/lib/python2.7/site-packages/numpy/ma/extras.py", line 592, in average
    "Axis must be specified when shapes of a and weights "
TypeError: Axis must be specified when shapes of a and weights differ.
```

My guess is that `ocgis` is not OK with latest `numpy`. I am trying to pin `numpy` to `<1.12` to test.

**Comment by bekozi** [comment]
That looks familiar and is caused by a newer version of `numpy`. Something changed in `ma.average`. I first noticed it in `1.11.2`. Fixed in the trunk, but not in this release.

**Comment by ocefpaf** [comment]
@bekozi it seems that you need `numpy <1.11` but `conda-forge` dropped support for that `numpy` to avoid strain on the CIs. That is a problem because we moved to `icu 58.*` , making the old `fiona`, compiled with `numpy 1.10` and icu `56.*` incompatible with the rest of the stack (`gdal` for example).

Maybe we could add a patch to make `ocgis` compatible with latest `numpy`?

**Comment by bekozi** [comment]
Crossing posts here...yeah, let me get a patch together...

**Comment by ocefpaf** [comment]
@bekozi I still see the failure with that patch :unamused: 

Do you want to merge this to get the feedsotck updates in and work on the patch in another PR?

**Comment by bekozi** [comment]
Patch is not being applied from what I gather. Any thoughts on why this may be happening? The failure is:

```
File "/feedstock_root/build_artefacts/recipe_root_1486657558700/_t_env/lib/python2.7/site-packages/ocgis/calc/base.py", line 119, in aggregate_spatial
    ret = np.ma.average(values, weights=weights)
```

Relevant patch line is:

https://github.com/conda-forge/ocgis-feedstock/pull/7/files#diff-73bbb073487aa6de16abad709c7f28d7R13

```
+-        ret = np.ma.average(values, weights=weights)
++        ret = np.ma.average(np.squeeze(values), weights=weights)
```

Target code line is not updated. Does it make sense to test the patch locally?

**Comment by ocefpaf** [comment]
> Patch is not being applied from what I gather.

The problem is that you got a bad reviewer (me :stuck_out_tongue_winking_eye:) who did not paid the proper attention. Commit https://github.com/conda-forge/ocgis-feedstock/pull/6/commits/b49159bb8f4635c51d03a1beb11d7747678469b1 should fix that.

**Comment by bekozi** [comment]
Confirmed this fix addresses the package naming issue. Thanks @ocefpaf for all the help!

**Pull request merged**
