### PR TITLE
Release v2.1.0

### PR DESCRIPTION
**Pull request by bekozi**

### CODE REVIEW

**Comment by bekozi** [comment]
@conda-forge-admin, please rerender circleci

**Comment by ocefpaf** [comment]
@bekozi here are the valide webservice:

https://conda-forge.org/docs/webservice.html

To update CircleCI you need to do it in an issue.

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by bekozi** [comment]
Thanks. I'm going to be mostly out for the next few days...so sorry in advance for the slow communications...

**Comment by ocefpaf** [comment]
> Thanks. I'm going to be mostly out for the next few days...so sorry in advance for the slow communications...

No problem. I can merge this once things are passing.

**Comment by bekozi** [comment]
:+1:

**Pull request merged**
