### PR TITLE
version 1.3.2

### PR DESCRIPTION
**Pull request by bekozi**
The latest commit is a placeholder until the release is tagged.

### CODE REVIEW

**Comment by ocefpaf** [comment]
LGTM. (You do know that it is fair game to self-merge updates PR, rught :wink:)

**Comment by bekozi** [comment]
Thanks @ocefpaf. I do know I can merge, but you are just quicker. I didn't even see the checks had finished! :smile:

**Comment by ocefpaf** [comment]
Oops. Sorry. (Having my coffee and merge after lunch :smile:)

**Comment by bekozi** [comment]
Quite alright! I am definitely not complaining. :relaxed:

**Pull request merged**
